name:                firestore
version:             0.1.0.0
github:              "githubuser/firestore"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
# - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/stonks#readme>

dependencies:
- base >= 4.7 && < 5
- lens
- bytestring
- time
- aeson
- aeson-pretty
- lens-aeson
- resourcet
- unordered-containers
- text
- gogol
- gogol-firestore
- http-types
- vector
- scientific
- QuickCheck
- generic-random
- quickcheck-instances


default-extensions:
# ghc2021
- EmptyCase
- PostfixOperators
- TupleSections
# - ImportQualifiedPost
- NamedFieldPuns
- BangPatterns
- BinaryLiterals
- HexFloatLiterals
- NumericUnderscores
- GADTSyntax
- RankNTypes
- TypeApplications
- PolyKinds
# - StandaloneKindSignatures
- ExistentialQuantification
- TypeOperators
- ConstraintKinds
- ExplicitForAll
- KindSignatures
- NamedWildCards
- ScopedTypeVariables
- FlexibleContexts
- FlexibleInstances
- MultiParamTypeClasses
- ConstrainedClassMethods
- InstanceSigs
- TypeSynonymInstances
- DeriveDataTypeable
- DeriveFoldable
- DeriveFunctor
- DeriveTraversable
- StandaloneDeriving
- EmptyDataDeriving
- DeriveLift
- GeneralisedNewtypeDeriving
- DeriveGeneric
# mine
- OverloadedStrings
- LambdaCase
- RecordWildCards

library:
  source-dirs: src

# executables:
#   stonks-exe:
#     main:                Main.hs
#     source-dirs:         app
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - stonks

tests:
  firestore-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - firestore
