name:                firestore
version:             0.1.0.0
github:              "valyagolev/firestore"
license:             BSD3
author:              "Valentin Golev"
maintainer:          "v.golev@gmail.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
# - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:          This is an arguably convenient wrapper around `Network.Google.FireStore`. This is likely not the idiomatic or best API for Google Firestore\/Datastore\/Firebase. I don't even understand the difference between all of those trademarks. Bug reports and suggestions are welcome. <https://github.com/valyagolev/firestore>

dependencies:
- base >= 4.7 && < 5
- lens
- bytestring
- time
- aeson
- lens-aeson
- resourcet
- unordered-containers
- text
- gogol
- gogol-firestore
- http-types
- vector

ghc-options:
- -fwarn-unused-imports

default-extensions:
# ghc2021
- EmptyCase
- PostfixOperators
- TupleSections
# - ImportQualifiedPost
- NamedFieldPuns
- BangPatterns
- BinaryLiterals
- HexFloatLiterals
- NumericUnderscores
- GADTSyntax
- RankNTypes
- TypeApplications
- PolyKinds
# - StandaloneKindSignatures
- ExistentialQuantification
- TypeOperators
- ConstraintKinds
- ExplicitForAll
- KindSignatures
- NamedWildCards
- ScopedTypeVariables
- FlexibleContexts
- FlexibleInstances
- MultiParamTypeClasses
- ConstrainedClassMethods
- InstanceSigs
- TypeSynonymInstances
- DeriveDataTypeable
- DeriveFoldable
- DeriveFunctor
- DeriveTraversable
- StandaloneDeriving
- EmptyDataDeriving
- DeriveLift
- GeneralisedNewtypeDeriving
- DeriveGeneric
# mine
- OverloadedStrings
- LambdaCase
- RecordWildCards

library:
  source-dirs: src

tests:
  firestore-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - firestore
    - aeson-pretty
    - QuickCheck
    - generic-random
    - quickcheck-instances
