name:                firestore
version:             0.1.0.0
github:              "valyagolev/firestore"
license:             BSD3
author:              "Valentin Golev"
maintainer:          "v.golev@gmail.com"
copyright:           "2021 Valentin Golev"
category:            Database, Google
synopsis:            Wrapper for Google Firestore/Datastore API

extra-source-files:
- README.md
# - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:          "This is an arguably convenient wrapper around gogols `Network.Google.FireStore`. This is likely not the idiomatic or best API for Google Firestore\/Datastore\/Firebase. I don't even understand the difference between all of those trademarks. Bug reports and suggestions are welcome. <https://github.com/valyagolev/firestore>"



dependencies:
- base                          >= 4.7 && < 5
- aeson                         >= 1.4.7.1 && < 1.6
- bytestring                    >= 0.10.10.1 && < 0.11
- text                          >= 1.2.4 && < 1.3
- time                          >= 1.9.3 && < 1.10
- unordered-containers          >= 0.2.10.0 && < 0.3
- vector                        >= 0.12.1.2 && < 0.13
- gogol                         >= 0.5.0 && < 0.6
- resourcet                     >= 1.2.4 && < 1.3
- http-types                    >= 0.12.3 && < 0.13
- lens                          >= 4.18.1 && < 5.1
- gogol-firestore               >= 0.5.0 && < 0.6
- lens-aeson                    >= 1.1 && < 1.2

ghc-options:
- -fwarn-unused-imports

default-extensions:
# ghc2021
- EmptyCase
- PostfixOperators
- TupleSections
# - ImportQualifiedPost
- NamedFieldPuns
- BangPatterns
- BinaryLiterals
- HexFloatLiterals
- NumericUnderscores
- GADTSyntax
- RankNTypes
- TypeApplications
- PolyKinds
# - StandaloneKindSignatures
- ExistentialQuantification
- TypeOperators
- ConstraintKinds
- ExplicitForAll
- KindSignatures
- NamedWildCards
- ScopedTypeVariables
- FlexibleContexts
- FlexibleInstances
- MultiParamTypeClasses
- ConstrainedClassMethods
- InstanceSigs
- TypeSynonymInstances
- DeriveDataTypeable
- DeriveFoldable
- DeriveFunctor
- DeriveTraversable
- StandaloneDeriving
- EmptyDataDeriving
- DeriveLift
- GeneralisedNewtypeDeriving
- DeriveGeneric
# mine
- OverloadedStrings
- LambdaCase
- RecordWildCards

library:
  source-dirs: src

tests:
  firestore-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - firestore
    - aeson-pretty
    - QuickCheck
    - generic-random
    - quickcheck-instances
